In [2]:
import torch
import torch.nn as nn
import torch.utils.data as tud
from tqdm.notebook import tqdm
from pprint import pprint
import matplotlib.pyplot as plt
import numpy as np
import importlib
import beam_search

In [3]:
# juana la loca

# with open("20099-8.txt", encoding = "latin-1") as file:
#     text = file.read()
# print(len(text))
# print(text[:1000])

In [4]:
# with open("64763-0.txt", encoding = "utf-8") as file:
#     text = file.read()
# print(len(text))
# print(text[:1000])

In [5]:
# chess

with open("data/pg5614.txt", encoding = "utf-8") as file:
    text = file.read()
print(len(text))
print(text[:100000])

556949
The Project Gutenberg EBook of Chess Strategy, by Edward Lasker

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.org/license


Title: Chess Strategy

Author: Edward Lasker

Translator: J. Du Mont

Release Date: November 11, 2012 [EBook #5614]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK CHESS STRATEGY ***




Produced by John Mamoun <mamounjo@umdnj.edu>, Charles
Franks, and the Online Distributed Proofreaders website.








INFORMATION ABOUT THIS E-TEXT EDITION



The following is an e-text of "Chess Strategy," second edition, (1915)
by Edward Lasker, translated by J. Du Mont.

This e-text contains the 167 chess and checkers board game
diagrams appearing in the original book, all in the form of
ASCII line drawings. The following is a key to the diagrams:

For chess

In [6]:
# with open("seq2seq.py", encoding = "utf-8") as file:
#     text = file.read()
# print(len(text))
# print(text[:1000])

In [7]:
len(text)

556949

In [8]:
vocabulary = set(text)
len(vocabulary)

92

In [9]:
char2i = {c:i for i, c in enumerate(sorted(vocabulary), 3)}
char2i["<PAD>"] = 0
char2i["<START>"] = 1
char2i["<END>"] = 2
print(len(char2i))
i2char = {i:c for i, c in enumerate(sorted(vocabulary), 3)}
i2char[0] = "<PAD>"
i2char[1] = "<START>"
i2char[2] = "<END>"
print(len(i2char))

95
95


In [10]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device

device(type='cuda')

In [11]:
length = 20
lines = []
for i in range(len(text))[:-length]:
    lines.append(text[i:length + i])
print(len(text))
print(len(lines))
print(lines[:5])
encoded = torch.tensor([[char2i[c] for c in l] for l in tqdm(lines)]).to(device).long()
print(encoded.shape)
source_1 = encoded[:, :length // 2]
print(source_1.shape)
target_1 = torch.cat((torch.ones(encoded.shape[0], 1).to(device).long(), encoded[:, length // 2:]), axis = 1)
print(target_1.shape)

556949
556929
['\ufeffThe Project Gutenbe', 'The Project Gutenber', 'he Project Gutenberg', 'e Project Gutenberg ', ' Project Gutenberg E']


  0%|          | 0/556929 [00:00<?, ?it/s]

torch.Size([556929, 20])
torch.Size([556929, 10])
torch.Size([556929, 11])


In [16]:
importlib.reload(beam_search)    
net = beam_search.Seq2SeqRNN(char2i, i2char, encoder_hidden_units = 100, decoder_hidden_units = 100)
net.to(device)
# net.load_state_dict(torch.load("models/save_transformer.pt"))
# net.eval()
# pprint([net.tensor2text(t) for t in net.beam_search(source_1[:2], 
#                                                     max_predictions = 5,
#                                                     candidates = 3,
#                                                     beam_width = 4)[0][:, :, 1:]])
# net.fit(source_1[:10], target_1[:10], epochs = 50, batch_size = 150, lr = 0.0001, verbose = 3)
net.fit(source_1, target_1, epochs = 50, batch_size = 150, lr = 0.0001, verbose = 3)
# net.fit(source_2, target_2, epochs = 10, batch_size = 100, lr = 0.00001, verbose = 2)
# net.fit(source_3, target_3, epochs = 10, batch_size = 100, lr = 0.00001)

Net parameters: 207,195


  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    1, Loss: 2.5302
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
[' eh  t   e', ' h  te  e ', '   eh  e e', '  th  e e ', ' th  e e  ']
greedy_search
['          ', '          ', '          ', '          ', '          ']
sample
['no\nice amU', 'gcithsspt ', 'ae the usw', 'h in gpitf', 'k a/  he  ']
beam_search
[['          ', '          ', '          ', '          ', '          '],
 ['         t', '         t', '        e ', 'e         ', 'e         '],
 ['        e ', '         a', '         a', '         t', '         t'],
 ['         e', '         h', '         e', ' e        ', '         K'],
 ['         a', '         e', '         t', '        e ', '         .']]
tensor([-11.1200, -10.9700, -12.1900,  -9.9900,  -9.2400], device='cuda:0')
tensor([[-11.1200, -10.9700, -12.1900,  -9.9900,  -9.2400],
        [-13.9100, -13.9300, -14.3600, -12.0700, -11.4700],
        [-14.0500, -14.0700, -14.5200, -12.3900, -11.5400],
        [-14.1400, -14.09

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    2, Loss: 1.9030
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
[' e aose  e', 'ehoole  e ', ' oole  e e', ' ele  e ee', ' le  e e a']
greedy_search
[' the the t', 'en the the', ' on the th', ' of the th', '  or the t']
sample
['mgibs sorp', 'anc. tamol', 'fing\n)ritt', 'bent. P-K,', ' me9mKtQ5.']
beam_search
[['s the the ', 'on the the', 'e the the ', 'e the the ', 'e the the '],
 [' the thes ', 'es the the', 'in the the', 'e the ther', ' the the t'],
 [' the the t', 'the the th', 'ing the th', ' of the th', ' the thes '],
 [' the there', 'on the thi', 'e the ther', 'e the thes', ' the there'],
 [' the the p', 'the the te', 'e the thes', ' of the an', ' the the a']]
tensor([-12.0000, -12.5600, -12.6700, -12.6700, -14.9800], device='cuda:0')
tensor([[-11.2500, -11.9700, -11.2300, -11.2600, -11.2500],
        [-11.9500, -11.9900, -12.2900, -12.5400, -12.1800],
        [-12.0000, -12.6200, -12.4200, -12.6700, -12.4300],
        [-12.4600, -13.72

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    3, Loss: 1.6240
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
[' e oute  e', 'ehoule  e ', 'eoale  e  ', 'eale  e e ', 'ele  e   t']
greedy_search
[' the the t', 'en the the', 'e the the ', 'e the the ', 'e the Kt-K']
sample
[' fobcti, t', 't ponterso', 'he\ngonn, a', 'rouenthr B', 'eers\nmant ']
beam_search
[['s the the ', 'on the the', 'e the the ', 'he the the', 'ing.\n\n    '],
 [' the the t', 'en the the', 'he the the', 'ing the th', 'e the the '],
 [' the the p', 'ond the th', 'his the th', 'his the th', 'ing the th'],
 [' the there', 'the the th', 'e the ther', 'he the thi', 'ing the Kt'],
 [' the thes ', 'ond the po', 'e the thes', 'his the pa', 'on the Kt-']]
tensor([-10.8000, -11.2100, -10.1100, -10.7800, -12.1700], device='cuda:0')
tensor([[-10.1300, -10.6300, -10.1100, -10.5400, -10.1600],
        [-10.8000, -11.2100, -10.3800, -11.5000, -11.0100],
        [-11.0400, -11.5200, -11.5200, -11.5800, -11.6700],
        [-11.1800, -11

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    4, Loss: 1.4901
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
[' e oute  y', 'n oute  e ', 'eaute  e  ', 'oute  e   ', 'ele  e   t']
greedy_search
[' the pawn ', 'n the pore', 'e the pawn', 'of the Kt-', 'enteren th']
sample
['t bestitio', ". BAck's t", 'co\n\nzGat, ', 'ants eferi', 'tiegd stak']
beam_search
[[' the the p', 'n the the ', 'e the the ', 'of the Bla', 'ing.\n\n    '],
 [' the the t', 's the the ', 'he the the', 'of the Kin', 'on the the'],
 [' the there', 'n the ther', 'e the ther', 'of the Kt-', 'ing. .....'],
 [' the pawn ', 's the ther', 'his the th', 'his the th', 'ing the th'],
 [' the the m', 'n the the\n', 'e the the\n', 'of the Ktx', 'ing the Kt']]
tensor([-11.0800, -12.2700, -10.7500, -10.1500, -13.7400], device='cuda:0')
tensor([[-10.1900,  -9.8100,  -8.8200,  -9.6200,  -9.2400],
        [-10.4400,  -9.9300,  -9.4800, -10.0500, -10.7000],
        [-11.0000, -11.1500, -10.4900, -10.1500, -10.9400],
        [-11.0800, -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    5, Loss: 1.4047
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
[' t outenty', 'n outenter', ' auten e  ', 'outerte   ', 'oterter  t']
greedy_search
[' the pawn ', 'n the pawn', ' and the p', 'of the Kt-', 'on the paw']
sample
[' move, of.', 'h nay by m', 'o welkes w', 'oncoupping', 'mantn:\n\n  ']
beam_search
[['n the pawn', 'n the the ', ' the King ', 'of the Bla', 'ing.\n\n    '],
 [' the pawn ', 'n the pawn', 'e the King', 'of the Kin', 'e the pawn'],
 ['s the pawn', 'n the pown', " the King'", 'of the Kt-', 'ing.\n\n   h'],
 ['d the pawn', 'n the ther', 'e the pawn', 'of the paw', 'e the pray'],
 ['n the pown', 'n the the\n', ' the King\n', 'on the paw', 'ing.\n\n   C']]
tensor([-10.4300,  -9.6600, -10.6900,  -9.5800, -11.9500], device='cuda:0')
tensor([[-10.1900,  -9.3200,  -9.3600,  -8.9600,  -9.0700],
        [-10.4300,  -9.6600,  -9.5000,  -8.9800, -11.4800],
        [-10.5200, -10.0800,  -9.7800,  -9.5800, -12.9600],
        [-10.740

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    6, Loss: 1.3441
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['nt outente', 'n tutenter', ' tuten er ', 'outentere ', 'otentere-t']
greedy_search
['n the pawn', 'n the pawn', ' the pawn ', 'on the paw', 'onterengen']
sample
['t (Nove., ', 'ftin: ind\n', ' in thare,', '9.\nRxP\nant', 'Furt geden']
beam_search
[['n the pawn', 'n the pawn', " the King'", 'of the Kin', 'ovent the '],
 ['n the pown', 'n the pown', ' the King ', 'of the paw', 'oventing t'],
 ['ng the paw', 'n the fore', ' in the pa', 'on the paw', 'ovent ther'],
 ['ng the Kti', 'n the pren', ' in there ', 'of the Kt-', 'oventing. '],
 ['n the Ktic', 'n the post', ' and the p', 'of the Kti', 'oventing.\n']]
tensor([ -9.6600,  -9.1700,  -9.8000,  -9.3900, -15.1200], device='cuda:0')
tensor([[ -9.6600,  -9.1700,  -8.8100,  -8.5500, -11.0300],
        [-10.6800,  -9.9800,  -9.0000,  -9.0200, -11.4000],
        [-11.0000, -10.3700,  -9.5200,  -9.3900, -11.9900],
        [-11.6400, -10

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    7, Loss: 1.2983
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['nt outente', 't tutenter', ' tutenter ', 'tutengere-', 'ottngerg-t']
greedy_search
['ng the paw', 't the pawn', ' the pawn ', 'the pawn t', 'ontereng-t']
sample
['se dinting', 't Fork. Bl', "'s forecod", 'of eng dia', 'tu-sNofty ']
beam_search
[['n the pawn', 'n the pawn', " the King'", 'of the Bla', 'e the pawn'],
 ['ng the Bla', 'k the pawn', ' the King ', "the King's", 'e the fore'],
 ['s to the p', 'n the pown', ' of the Ki', 'of the Kin', 'e there to'],
 ['ng the paw', 'n the post', ' the pawn ', 'of the paw', 'e there fo'],
 ['s to the t', 'n there th', ' in the pa', 'the King t', 'e there th']]
tensor([-10.6600, -10.1100,  -9.1200,  -9.6300, -13.9000], device='cuda:0')
tensor([[ -9.7700,  -9.0600,  -8.1900,  -8.0100, -10.9400],
        [ -9.8400,  -9.6800,  -8.4700,  -8.0500, -11.4000],
        [-10.2200, -10.1500,  -8.8200,  -8.1200, -12.0700],
        [-10.6600, -10.850

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    8, Loss: 1.2613
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['te Gutente', 't tutenter', ' tutenter ', 'tutengerg ', 'ottngerg-t']
greedy_search
['t to the p', 't to the p', ' the pawn ', 'the pawn t', 'ontereng-t']
sample
['m (nibeena', 'd Site fir', " Whatee's ", 'Guterve GA', 'Gutenian: ']
beam_search
[['ng to the ', 'n the pawn', " the King'", 'of the Bla', 'antergent '],
 ['d to the p', 'k the pawn', ' of the pa', 'of the paw', 'oventeng t'],
 ['t to the p', 'n the pown', ' the King ', 'of the Kin', 'antergente'],
 ['ng the paw', 'k there th', ' in there ', 'the pawns ', 'antergenti'],
 ['ng to ther', 'n the post', ' of the Ki', 'the pawn t', 'oventengen']]
tensor([-10.6700, -10.2700,  -8.6000,  -9.2900, -13.4800], device='cuda:0')
tensor([[ -9.6300,  -9.4100,  -8.0300,  -8.2300, -12.4900],
        [-10.6000,  -9.7300,  -8.6800,  -8.3700, -12.6900],
        [-10.6700, -10.5900,  -8.7800,  -8.5900, -12.9900],
        [-11.1500, -11.120

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    9, Loss: 1.2302
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['te Gutente', 't tutenter', ' tutenterg', 'tutengerg-', 'ottngerg-t']
greedy_search
['t Gutent a', 't to the p', ' the pawn ', 'the pawn t', 'onentergen']
sample
['.\n\n     Bx', ',\n9. This ', '. NStameri', 'attery ref', '. 7. B-Kt5']
beam_search
[['t to the p', 't Gutenter', " the King'", 'of the Bla', 'anterg-t5 '],
 ['d by the p', 't Gutentre', ' the pawn ', 'of the Kin', 'antergent '],
 ['t Gutent a', 't Gutenent', ' the King ', 'of the paw', 'anterg-t5\n'],
 ['t Guteng t', 't Gutenten', ' of the pa', 'the pawns ', 'atereng-t5'],
 ['t Gutent b', 't Gutent b', ' of the Ki', 'the pawn t', 'antergenti']]
tensor([-10.8400, -10.0300,  -8.6700,  -9.1200, -14.1100], device='cuda:0')
tensor([[-10.4800,  -9.9100,  -8.1000,  -8.0200, -12.1100],
        [-10.5600, -10.1900,  -8.6700,  -8.1000, -12.8700],
        [-10.8400, -10.3700,  -8.7200,  -8.1300, -12.9100],
        [-10.8700, -10

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   10, Loss: 1.2033
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['te Gutente', 't Gutenter', ' tutenterg', 'tutenterg ', 'etengerg-t']
greedy_search
['t Gutent b', 't Gutenter', ' the pawn ', 'the pawn a', 'e toure to']
sample
['len sfoudt', 't. Lincend', 's White de', 'B4, Aftere', 'astrefreg ']
beam_search
[['t Gutenter', 't Gutenter', " the King'", "the King's", 'anterg-t5 '],
 ['t Gutent b', 't Gutentre', ' the King ', 'of the paw', 'anterg-t5\n'],
 ['t Gutent G', 't Gutenent', ' in there ', 'the pawns ', 'anterg-tm '],
 ['t Gutent a', 't Gutenten', ' of the pa', 'the King t', 'antergent '],
 ['t Gutenger', 't Gutented', ' of the Ki', 'the pawn a', 'atereng-t5']]
tensor([ -9.8000,  -8.2700,  -8.7600,  -9.2100, -13.0000], device='cuda:0')
tensor([[ -9.4300,  -8.2700,  -8.3000,  -7.5500, -12.1900],
        [ -9.8000,  -8.8700,  -8.5900,  -8.2600, -12.9100],
        [ -9.8200,  -9.2000,  -8.6400,  -8.8600, -12.9700],
        [ -9.9100,  -9.33

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   11, Loss: 1.1800
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['te Gutente', 't Gutenter', ' tutenterg', 'tutengerg-', 'etengerg-t']
greedy_search
['t Gutent G', 't Gutenter', ' to the pa', 'the pawn b', 'e better b']
sample
["n's sfaldr", 'ipte. Al\ni', '. It rerta', ' would be ', 'itengrtett']
beam_search
[['t Gutenter', 't Gutenter', ' the pawn ', "the King's", 'omentergem'],
 ['t Gutent G', 't Gutenber', ' in the pa', 'of the paw', 'omenterger'],
 ['nt Gutent ', 't Gutenten', ' the pawns', 'the pawns ', 'omenterg-t'],
 ['t Gutenger', 't Gutenger', ' in there ', 'the pawn b', 'omentergen'],
 ['t Gutent b', 't Gutented', ' to the pa', 'the pawn a', 'omentergat']]
tensor([ -8.8900,  -7.4200,  -9.2800,  -8.8900, -14.3600], device='cuda:0')
tensor([[ -8.8800,  -7.4200,  -8.6500,  -7.4100, -11.9800],
        [ -8.8900,  -8.2000,  -8.8600,  -7.9900, -12.0600],
        [ -9.0300,  -8.6200,  -8.8900,  -8.7000, -12.1100],
        [ -9.1600,  -8.83

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   12, Loss: 1.1595
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tt Gutente', 't Gutenter', ' tutenterg', 'tutengerg ', 'etengerg-t']
greedy_search
['t Gutent G', 't Gutenter', ' to the pa', 'the pawn b', 'e better g']
sample
['s to oneti', 't\nby dequr', 'ing andigh', 'Disent be ', 'ext of Dit']
beam_search
[['t Gutenter', 't Gutenter', ' of the pa', 'of the Kin', 'omenterger'],
 ['t Gutenger', 't Gutenber', ' of the Ki', 'of the paw', 'omenterg-t'],
 ['t Gutent G', 't Gutenten', ' of the Kn', 'of the Que', 'omentergem'],
 ['t Gutenge ', 't Gutenger', ' of the Bl', 'the pawns ', 'omentergen'],
 ['t Gutenged', 't Gutented', ' of the Qu', 'the pawn b', 'omenterget']]
tensor([ -8.6000,  -6.7900,  -9.4200,  -8.8800, -13.2800], device='cuda:0')
tensor([[ -8.3400,  -6.7900,  -8.3200,  -7.9400, -11.2000],
        [ -8.5700,  -7.1100,  -8.4000,  -8.0800, -11.5200],
        [ -8.6000,  -7.9800,  -8.4300,  -8.4000, -11.6000],
        [ -8.6700,  -8.11

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   13, Loss: 1.1411
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tt Gutente', 't Gutenter', ' tutenterg', 'tutengerg ', 'etengerg-t']
greedy_search
['t Gutent G', 't Gutenter', ' to the pa', 'the pawn b', 'efenterger']
sample
['gtips I si', 't.\n\n      ', '?) (Befwe:', 'opening be', 'tatter. "T']
beam_search
[['t Gutenber', 't Gutenber', ' Gutenberg', 'of the paw', 'utenterger'],
 ['t Gutenter', 't Gutenter', ' Gutenter ', 'of the Kin', 'utentergem'],
 ['t Gutenger', 't Gutented', ' Gutentere', 'of the Kni', 'utengerget'],
 ['t Gutenged', 't Gutente ', ' Gutenterg', 'the pawns ', 'utenterget'],
 ['t Gutenge ', 't Gutenger', ' Gutenter\n', 'the pawn b', 'utengergem']]
tensor([ -8.2300,  -6.1500,  -9.4800,  -8.7600, -12.2200], device='cuda:0')
tensor([[ -7.3200,  -6.0500,  -7.3300,  -7.9500, -10.8400],
        [ -7.7000,  -6.1500,  -8.5100,  -8.1100, -11.2600],
        [ -8.0900,  -7.3700,  -9.4200,  -8.4100, -11.2900],
        [ -8.1300,  -7.

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   14, Loss: 1.1246
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tt Gutente', 't Gutenter', ' Gutenterg', 'tutengerg ', 'etengerg-t']
greedy_search
['t Gutenter', 't Gutenter', ' Gutenter ', 'the pawn b', 'efenterger']
sample
['ng moved m', 't Game bet', ' hawing\nI ', 'pishose. A', 'efwereodse']
beam_search
[['t Gutenber', 't Gutenber', ' Gutenberg', 'of the paw', 'utenberg-t'],
 ['t Gutenter', 't.\n\n      ', ' Gutenter ', 'of the Kin', 'utenberg-b'],
 ['t Gutenger', 't Gutenter', ' Gutentere', 'of the Kni', 'utenberg-g'],
 ['t Gutenged', 't Gutente ', ' Gutenberd', 'the pawn b', 'utenberg--'],
 ['t Gutenge ', 't Gutenger', ' Gutenber ', 'the pawns ', 'utenberget']]
tensor([ -7.3400,  -5.9300,  -8.3300,  -8.5500, -11.7200], device='cuda:0')
tensor([[ -6.5700,  -5.3000,  -6.6900,  -7.8600,  -7.9600],
        [ -7.3400,  -5.5400,  -8.3300,  -7.9800,  -9.9300],
        [ -7.8000,  -5.9300,  -9.2500,  -8.1000, -10.0000],
        [ -8.0100,  -7.

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   15, Loss: 1.1097
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tk Gutente', 't Gutenber', ' Gutenberg', 'tutenberg-', 'etenberg-t']
greedy_search
['t Gutenber', 't Gutenber', ' Gutenberg', 'the pawn b', 'efereent G']
sample
['ng Game Gu', 'h\nBxB then', '\nuffttre.\n', 'oretent of', 'arteregDat']
beam_search
[['t Gutenber', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenter', 't.\n\n      ', ' Gutenter ', 'Gutenberg ', 'utenberg-b'],
 ['t Gutenger', 't Gutenter', ' Gutenberd', 'of the Kni', 'utenberg-g'],
 ['t Gutented', 't Gutenbee', ' of the Kn', "Gutenberg'", 'utenberg--'],
 ['t Gutenge ', 't Gutente ', ' Gutenber-', 'Gutenberg,', 'utenberget']]
tensor([ -5.7800,  -4.3400,  -5.4000,  -8.7200, -11.7000], device='cuda:0')
tensor([[-5.7800, -4.3400, -5.4000, -7.1700, -6.9700],
        [-6.8300, -5.3500, -7.8100, -7.3300, -9.0100],
        [-7.4000, -5.4600, -8.0900, -8.0100, -9.0300],
        [-7.8300, -6.5900, -8.1700, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   16, Loss: 1.0961
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tk Gutenbe', 't Gutenber', ' Gutenberg', 'tutenberg ', 'etenberg-L']
greedy_search
['t Gutenber', 't Gutenber', ' Gutenberg', 'the pawn b', 'ementerger']
sample
['fworer, 9.', 'nevouding,', ' befent). ', 'White Reek', '\nAbtibtegz']
beam_search
[['t Gutenber', 't Gutenber', '.\n\n       ', 'Gutenberg ', 'utenberg-t'],
 ['ng Gutenbe', 't.\n\n      ', ' Gutenberg', 'Gutenberg-', 'utenberget'],
 ['t Gutenter', 't Gutenbee', ' Gutenberd', "Gutenberg'", 'utenberg-b'],
 ['ck Gutenbe', 't Gutenter', ' Gutenber-', 'Gutenberg,', 'utenberg-g'],
 ['t Gutenbee', 't Gutenbel', ' Gutenber ', 'Gutenberge', 'utenberg L']]
tensor([ -5.2000,  -3.7500,  -4.5900,  -8.8200, -11.0100], device='cuda:0')
tensor([[-5.2000, -3.7500, -4.2600, -6.3800, -6.3700],
        [-6.9800, -5.2100, -4.5900, -6.4600, -8.5300],
        [-7.0300, -5.7500, -7.1200, -7.0500, -8.5900],
        [-7.2000, -5.8600, -7.3700, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   17, Loss: 1.0835
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tk Gutenbe', 't Gutenber', ' Gutenberg', 'tutenberg ', 'utenberg-L']
greedy_search
['t Gutenber', 't Gutenber', ' Gutenberg', 'to the paw', 'utenberg-t']
sample
['ct\nGutenbi', 't GHeingne', 'urrent fir', 'beartiby g', 'utteet OS.']
beam_search
[['t Gutenber', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg-t'],
 ['ck Gutenbe', 't Gutenbee', ' Gutenberd', 'Gutenberg-', 'utenberget'],
 ['t Gutenter', 't Gutenter', ' Gutenber ', "Gutenberg'", 'utenberg-g'],
 ['t Gutenbee', 't Gutenbel', ' Gutenber-', 'Gutenberg,', 'utenberg L'],
 ['ng Gutenbe', 't Gutente ', ' Gutenbere', 'Gutenberg.', 'utenberg-b']]
tensor([-4.7900, -3.3200, -4.1700, -9.0300, -5.7500], device='cuda:0')
tensor([[-4.7900, -3.3200, -4.1700, -6.0300, -5.7500],
        [-6.8300, -5.5100, -6.5800, -6.1400, -7.8600],
        [-7.0000, -5.9400, -6.8300, -6.6500, -8.1000],
        [-7.0300, -6.3800, -7.0200, -6.9000, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   18, Loss: 1.0718
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tt Gutenbe', 't Gutenber', ' Gutenberg', 'tutenberg-', 'utenberg-L']
greedy_search
['t Gutenber', 't Gutenber', ' Gutenberg', 'the pawn b', 'utenberg-t']
sample
['gart-:mate', "tion's Dif", '\nattenge G', 'II DeLitDi', 'uteekenbbr']
beam_search
[['t Gutenber', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct Gutenbe', 't Gutenbee', ' Gutenberd', 'Gutenberg ', 'utenberg L'],
 ['ct Gutente', 't\nGutenber', ' Gutenber-', "Gutenberg'", 'utenberg-g'],
 ['t Gutenbee', 't Gutenter', ' Gutenber ', 'Gutenberg,', 'utenberg-b'],
 ['t Gutenter', 't Gutenbel', ' Gutenbere', 'Gutenberg.', 'utenberg t']]
tensor([-4.3600, -2.8500, -3.5500, -8.5700, -5.0600], device='cuda:0')
tensor([[-4.3600, -2.8500, -3.5500, -5.3400, -5.0600],
        [-5.0300, -5.0800, -6.1800, -5.4500, -7.2200],
        [-6.3500, -5.3500, -6.3600, -6.1800, -7.4000],
        [-6.6400, -5.5900, -6.5800, -6.2700,

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   19, Loss: 1.0609
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tt Gutenbe', 't Gutenber', ' Gutenberg', 'tutenberg-', 'utenberg-L']
greedy_search
['t Gutenber', 't Gutenber', ' Gutenberg', 'to be game', 'utenberg-t']
sample
[' not game,', 'k afere at', ' Gutenberg', 'ceition ed', 'uttrer--He']
beam_search
[['t Gutenber', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct Gutenbe', 't Gutenbee', '.\n\n       ', 'Gutenberg ', 'utenberg L'],
 ['me.\n\n     ', 't\nGutenber', ' Gutenber ', "Gutenberg'", 'utenberg\nt'],
 ['ck Gutenbe', 't Gutenbel', ' Gutenber-', 'Gutenberg,', 'utenberg-g'],
 ['ct Gutente', 't Gutenter', ' Gutenberd', 'Gutenberg.', 'utenberget']]
tensor([ -4.2800,  -2.5900,  -3.3000, -10.0500,  -4.5200], device='cuda:0')
tensor([[-4.2800, -2.5900, -3.3000, -5.0700, -4.5200],
        [-4.6700, -4.7800, -4.5100, -5.3000, -6.7300],
        [-5.6300, -5.0600, -6.0300, -5.7200, -6.9500],
        [-6.1000, -5.5400, -6.1700,

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   20, Loss: 1.0507
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['tt Gutenbe', 't Gutenber', ' Gutenberg', 'tutenberg-', 'utenberg-L']
greedy_search
['t Gutenber', 't Gutenber', ' Gutenberg', 'to the paw', 'utenberg-t']
sample
['ct Gutenbe', 'ce with 1.', ' of\nProjec', 'the move T', 'eventen\n\n ']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't Gutenbee', ' Gutenber ', 'Gutenberg ', 'utenberg L'],
 ['ct Gutente', 't\nGutenber', ' Gutenberd', "Gutenberg'", 'itenberg-t'],
 ['ck Gutenbe', 't Gutenbel', ' Gutenber-', 'Gutenberg,', 'utenberg t'],
 ['t Gutenbel', 't Gutenter', ' Gutenber.', 'Gutenberg.', 'utenberg\nt']]
tensor([-4.2500, -2.4300, -3.1600, -8.8600, -4.2400], device='cuda:0')
tensor([[-4.2400, -2.4300, -3.1600, -4.8600, -4.2400],
        [-4.2500, -4.9200, -5.8800, -4.9800, -6.3200],
        [-5.7400, -4.9700, -5.9700, -5.6200, -6.3300],
        [-5.8700, -5.6000, -6.2100, -5.89

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   21, Loss: 1.0412
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['gefores, W', 't of lefft', ' Gutengeng', 'KtxP, erke', 'utenge\nten']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't Gutenbee', ' Gutenberd', 'Gutenberg ', 'utenberg L'],
 ['ck Gutenbe', 't\nGutenber', ' Gutenber ', "Gutenberg'", 'utenberg\nt'],
 ['ct Gutente', 't.\n\n      ', ' Gutenber-', 'Gutenberg,', 'utenberg t'],
 ['t Gutenbel', 't Gutenbel', ' Gutenbere', 'Gutenberg.', 'utenberget']]
tensor([-3.7700, -2.1400, -2.6500, -4.2100, -3.8100], device='cuda:0')
tensor([[-3.7700, -2.1400, -2.6500, -4.2100, -3.8100],
        [-4.0100, -4.4600, -5.8100, -4.6100, -5.7700],
        [-5.4700, -4.6700, -5.8600, -5.2800, -6.1900],
        [-5.6200, -4.8600, -6.0300, -5.43

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   22, Loss: 1.0322
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['): Onengra', 'en equintu', ' This pirc', 'Afecentrem', 'ifforely b']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't\nGutenber', ' Gutenber ', 'Gutenberg ', 'utenberg L'],
 ['ct Gutente', 't Gutenbee', ' Gutenberd', 'Gutenberg,', 'utenberg\nt'],
 ['ck Gutenbe', 't.\n\n      ', ' Gutenber-', "Gutenberg'", 'utenberget'],
 ['t Gutenbel', 't Gutenbel', ' Gutenbele', 'Gutenberg.', 'utenberg.\n']]
tensor([-3.5400, -2.1300, -2.5000, -3.7900, -3.4600], device='cuda:0')
tensor([[-3.5400, -2.1300, -2.5000, -3.7900, -3.4600],
        [-4.2000, -4.5500, -5.6800, -4.4000, -5.5800],
        [-5.4300, -4.6700, -5.6900, -5.2200, -6.0100],
        [-5.5100, -4.8500, -5.8100, -5.39

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   23, Loss: 1.0238
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ng.   BxBP', 'n.   Theed', '\nGutenber-', 'frestuberg', 'uvenberg\nL']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't\nGutenber', '.\n\n       ', 'Gutenberg ', 'utenberg L'],
 ['ck Gutenbe', 't Gutenbee', ' Gutenber-', "Gutenberg'", 'utenberg.\n'],
 ['ct Gutente', 't.\n\n      ', ' Gutenberd', 'Gutenberg.', 'utenberg\nt'],
 ['ct Gutenge', 't Gutenbel', ' Gutenber ', 'Gutenberg,', 'utenberg-L']]
tensor([-3.2900, -1.8100, -2.1000, -3.3600, -3.2000], device='cuda:0')
tensor([[-3.2900, -1.8100, -2.1000, -3.3600, -3.2000],
        [-4.0800, -4.1900, -4.2600, -4.2000, -5.5000],
        [-4.9100, -4.6800, -5.4500, -4.7300, -5.8100],
        [-5.5200, -4.7400, -5.6000, -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   24, Loss: 1.0158
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['me, prited', 't\nGutente.', '."\n\nThe pa', 'mitticuede', 'eanted Lit']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't\nGutenber', ' Gutenber-', 'Gutenberg ', 'utenberg L'],
 ['ct Gutente', 't Gutenbee', ' Gutenber ', "Gutenberg'", 'utenberg.\n'],
 ['ck Gutenbe', 't.\n\n      ', ' Gutenberd', 'Gutenberg,', 'utenberg-L'],
 ['ct Gutenge', 't Gutenbel', ' Gutenbele', 'Gutenberg.', 'utenberg\nt']]
tensor([-2.9200, -1.8200, -2.1500, -3.2500, -2.9000], device='cuda:0')
tensor([[-2.9200, -1.8200, -2.1500, -3.2500, -2.9000],
        [-4.1100, -4.1100, -5.4000, -4.4500, -5.3500],
        [-4.7600, -4.6800, -5.6000, -4.9700, -5.6500],
        [-5.4900, -5.0100, -5.7600, -5

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   25, Loss: 1.0084
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ck dLay Cu', 't Gutenber', ' defencedo', '|\n   White', 'tefergremp']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't\nGutenber', ' Gutenber-', 'Gutenberg ', 'utenberg L'],
 ['ct Gutente', 't Gutenbee', ' Gutenber ', 'Gutenberg,', 'utenberg t'],
 ['ck Gutenbe', 't.\n\n      ', ' Gutenberd', "Gutenberg'", 'utenberg\nt'],
 ['ct Gutenge', 't Gutenbel', ' Gutenbele', 'Gutenberg.', 'utenberg.\n']]
tensor([-2.6700, -1.6100, -1.9400, -3.0100, -2.7000], device='cuda:0')
tensor([[-2.6700, -1.6100, -1.9400, -3.0100, -2.7000],
        [-4.0600, -3.9000, -5.6500, -3.7500, -4.7400],
        [-4.7200, -4.5600, -5.7900, -4.6800, -5.3700],
        [-5.0400, -4.8400, -5.8100, -4.7

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   26, Loss: 1.0013
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gitingr, ', 'verioged.\n', ' 5. 6.\n\nTr']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['t Gutenber', 't\nGutenber', ' Gutenber-', 'Gutenberg ', 'utenberg L'],
 ['ct Gutente', 't Gutenbee', ' Gutenber ', "Gutenberg'", 'utenberg-L'],
 ['ck Gutenbe', 't.\n\n      ', ' Gutenberd', 'Gutenberg.', 'utenberg.\n'],
 ['ct Gutenge', 't Gutenbel', ' Gutenbele', 'Gutenberg,', 'utenberg t']]
tensor([-2.5500, -1.4300, -1.6600, -2.7000, -2.3900], device='cuda:0')
tensor([[-2.5500, -1.4300, -1.6600, -2.7000, -2.3900],
        [-3.9700, -3.7000, -5.2700, -3.7300, -4.6100],
        [-4.7600, -4.5800, -5.5400, -4.4000, -5.2800],
        [-5.0000, -4.9000, -5.7000, -4.

  0%|          | 0/3713 [00:00<?, ?it/s]

KeyboardInterrupt: 