In [1]:
import torch
import torch.nn as nn
import torch.utils.data as tud
from tqdm.notebook import tqdm
from pprint import pprint
import matplotlib.pyplot as plt
import numpy as np
import importlib
import beam_search

In [2]:
# juana la loca

# with open("20099-8.txt", encoding = "latin-1") as file:
#     text = file.read()
# print(len(text))
# print(text[:1000])

In [3]:
# with open("64763-0.txt", encoding = "utf-8") as file:
#     text = file.read()
# print(len(text))
# print(text[:1000])

In [4]:
# chess

with open("data/pg5614.txt", encoding = "utf-8") as file:
    text = file.read()
print(len(text))
print(text[:100000])

556949
The Project Gutenberg EBook of Chess Strategy, by Edward Lasker

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.org/license


Title: Chess Strategy

Author: Edward Lasker

Translator: J. Du Mont

Release Date: November 11, 2012 [EBook #5614]

Language: English


*** START OF THIS PROJECT GUTENBERG EBOOK CHESS STRATEGY ***




Produced by John Mamoun <mamounjo@umdnj.edu>, Charles
Franks, and the Online Distributed Proofreaders website.








INFORMATION ABOUT THIS E-TEXT EDITION



The following is an e-text of "Chess Strategy," second edition, (1915)
by Edward Lasker, translated by J. Du Mont.

This e-text contains the 167 chess and checkers board game
diagrams appearing in the original book, all in the form of
ASCII line drawings. The following is a key to the diagrams:

For chess

In [5]:
# with open("seq2seq.py", encoding = "utf-8") as file:
#     text = file.read()
# print(len(text))
# print(text[:1000])

In [6]:
len(text)

556949

In [7]:
vocabulary = set(text)
len(vocabulary)

92

In [8]:
char2i = {c:i for i, c in enumerate(sorted(vocabulary), 3)}
char2i["<PAD>"] = 0
char2i["<START>"] = 1
char2i["<END>"] = 2
print(len(char2i))
i2char = {i:c for i, c in enumerate(sorted(vocabulary), 3)}
i2char[0] = "<PAD>"
i2char[1] = "<START>"
i2char[2] = "<END>"
print(len(i2char))

95
95


In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device

device(type='cuda')

In [10]:
length = 20
lines = []
for i in range(len(text))[:-length]:
    lines.append(text[i:length + i])
print(len(text))
print(len(lines))
print(lines[:5])
encoded = torch.tensor([[char2i[c] for c in l] for l in tqdm(lines)]).to(device).long()
print(encoded.shape)
source_1 = encoded[:, :length // 2]
print(source_1.shape)
target_1 = torch.cat((torch.ones(encoded.shape[0], 1).to(device).long(), encoded[:, length // 2:]), axis = 1)
print(target_1.shape)

556949
556929
['\ufeffThe Project Gutenbe', 'The Project Gutenber', 'he Project Gutenberg', 'e Project Gutenberg ', ' Project Gutenberg E']


  0%|          | 0/556929 [00:00<?, ?it/s]

torch.Size([556929, 20])
torch.Size([556929, 10])
torch.Size([556929, 11])


In [11]:
importlib.reload(beam_search)    
net = beam_search.Transformer(char2i, i2char, embedding_dimension = 100, encoder_layers = 2, decoder_layers = 2)
net.to(device)
# net.load_state_dict(torch.load("models/save_transformer.pt"))
# net.eval()
# pprint([net.tensor2text(t) for t in net.beam_search(source_1[:2], 
#                                                     max_predictions = 5,
#                                                     candidates = 3,
#                                                     beam_width = 4)[0][:, :, 1:]])
# net.fit(source_1[:10], target_1[:10], epochs = 50, batch_size = 150, lr = 0.0001, verbose = 3)
net.fit(source_1, target_1, epochs = 50, batch_size = 150, lr = 0.0001, verbose = 3)
# net.fit(source_2, target_2, epochs = 10, batch_size = 100, lr = 0.00001, verbose = 2)
# net.fit(source_3, target_3, epochs = 10, batch_size = 100, lr = 0.00001)

Net parameters: 1,940,887


  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    1, Loss: 1.5242
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
[' t outente', 't tutenter', ' tutenter ', 'tutenterg-', 'openterg-t']
greedy_search
[' the pawns', 't the pawn', ' the pawn ', 'the pawn t', 'ound the p']
sample
[' i groum t', 'uction bac', ' of would ', 'prove. 5. ', 'or Kt(Came']
beam_search
[['ct of the ', 't the pawn', ' the pawn ', "the King's", 'upposition'],
 [' pawn the ', 'tion the p', ' the pawns', 'the pawns ', 'upporting '],
 ['ction the ', 'tions the ', ' of the pa', 'the pawn t', 'or the paw'],
 [' the pawns', 't the King', 'ion the pa', 'the Queen ', 'ound the p'],
 [' the pawn ', 't of the p', ' of the Ki', 'the pawn a', 'ound the K']]
tensor([ -8.1500,  -8.0200,  -7.8000,  -7.8800, -10.2800], device='cuda:0')
tensor([[ -7.5500,  -8.0200,  -7.8000,  -6.8700,  -7.1400],
        [ -7.6100,  -8.2500,  -8.0600,  -7.4900,  -8.8800],
        [ -7.7700,  -8.3500,  -8.2200,  -7.8800,  -9.5000],
        [ -8.1500,  -8.400

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    2, Loss: 1.1577
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\n     12', 't, 88.\n\n\n ', 's of the d', "Black's P-", 'orted move']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct Gutent ', 't\nGutenber', '\n\n        ', 'Gutenberg ', 'utenberg, '],
 ['ct Gutence', 't Gutence ', ' Gutenber ', 'Gutenberg,', 'utenberg t'],
 ['ct Gutend ', 't Gutend t', ' Gutent of', 'Gutenberg\n', 'utenberg\n\n'],
 ['ct Gutenba', 't Gutent o', ' Gutenbere', 'Gutent of ', 'utenberg.\n']]
tensor([-2.5200, -2.8400, -2.8900, -4.3400, -3.2000], device='cuda:0')
tensor([[-2.5200, -2.8400, -2.8900, -4.3400, -3.2000],
        [-4.1300, -5.0900, -3.9400, -5.7800, -6.1800],
        [-4.5700, -5.4900, -6.7500, -6.9700, -6.4600],
        [-5.1300, -6.6400, -6.7800,

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    3, Loss: 1.0685
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Forker-M', ' Gutenberg', 'GuMberg to', 'utenberg o']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg\n\n'],
 ['ct Gutenba', 't.\n\n      ', 'enberg-tm ', 'Gutenberg\n', 'utenberg, '],
 ['ct Gutened', 't Gutenbar', 'enberg-tm\n', 'Gutenberg,', 'otenberg-t'],
 ['ct Gutenen', 't Gutenben', ' Gutenbere', 'Gutenberge', 'utenberg L']]
tensor([-0.7000, -0.8200, -0.8500, -1.1100, -0.9200], device='cuda:0')
tensor([[-0.7000, -0.8200, -0.8500, -1.1100, -0.9200],
        [-2.9300, -3.6500, -3.0400, -3.2700, -4.4800],
        [-5.1000, -4.9500, -4.7700, -4.2800, -4.8400],
        [-5.8300, -5.8000, -6.4400, -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    4, Loss: 1.0171
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg\n\n'],
 ['ct.\n\n     ', 't.\n\n      ', ' Gutenbarg', 'Gutenberg\n', 'utenberg L'],
 ['ct Gutenba', 't Gutenbar', ' Gutenbed ', 'Gutenberg,', 'utenberg, '],
 ['ct Gutenby', 't Gutenby ', ' Gutenber ', 'Gutenberg.', 'utenberg (']]
tensor([-0.4300, -0.4400, -0.4800, -0.4300, -0.5400], device='cuda:0')
tensor([[-0.4300, -0.4400, -0.4800, -0.4300, -0.5400],
        [-2.4400, -3.2400, -3.1900, -3.0300, -4.3100],
        [-5.0900, -5.4300, -6.7600, -3.9400, -4.6500],
        [-5.1400, -5.8300, -6.8300, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    5, Loss: 0.9808
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't, and 190', '\nGutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg\n\n'],
 ['ct.\n\n     ', 't.\n\n      ', '.\n\n       ', 'Gutenberg\n', 'utenberg L'],
 ['ct Gutenba', 't Gutenbed', ' Gutenber ', 'Gutenberg,', 'utenberg, '],
 ['ct Gutenby', 't Gutenby ', ' Gutenbed ', 'Gutenberg.', 'utenberg.\n']]
tensor([-0.3800, -0.3000, -0.3900, -0.4100, -0.4000], device='cuda:0')
tensor([[-0.3800, -0.3000, -0.3900, -0.4100, -0.4000],
        [-2.2300, -2.7400, -2.7400, -2.5800, -3.4300],
        [-4.7400, -5.2700, -4.7700, -3.3000, -3.9500],
        [-6.3400, -5.9900, -6.35

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    6, Loss: 0.9531
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct.\nThe ne', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ',
  't.\n\n      ',
  '.\n\n       ',
  'Gutenberg\n',
  'utenberg\n\n'],
 ['ct Gutenba', 't Gutenbed', ' Gutenbed ', 'Gutenberg,', 'utenberg, '],
 ['ct Gutenby', 't Gutenby ', ' Gutenbed,', 'Gutenberg.', 'utenberg\nL']]
tensor([-0.2300, -0.2100, -0.2700, -0.3200, -0.2900], device='cuda:0')
tensor([[-0.2300, -0.2100, -0.2700, -0.3200, -0.2900],
        [-2.7400, -2.7500, -3.1200, -2.3700, -3.6100],
        [-5.2300, -5.6900, -4.9100, -3.5100, -4.3900],
        [-5.5500, -5.840

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    7, Loss: 0.9306
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ',
  't\n\n       ',
  '\n\n        ',
  'Gutenberg\n',
  'utenberg\n\n'],
 ['ct Gunberg', 't Gunberg-', ' Gunberg-t', 'Gutenberg,', 'utenberg\nL'],
 ['ct Gutenba', 't Gutenbed', ' Gutenbute', 'Gutenberg.', 'utenberg, ']]
tensor([-0.2600, -0.2700, -0.2600, -0.2500, -0.2400], device='cuda:0')
tensor([[-0.2600, -0.2700, -0.2600, -0.2500, -0.2400],
        [-2.0600, -1.9800, -2.0000, -2.4400, -3.0300],
        [-5.8900, -6.2200, -5.8000, -3.2800, -3.7800],
        [-5.9100, -6.380

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    8, Loss: 0.9120
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'of this eW', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct Gutenba', 't.\n\n      ', '-Gutenberg', 'Gutenberg\n', 'utenberg\nL'],
 ['ct.\n\n     ', 't Gutenbed', 'ive Gutenb', 'Gutenberg"', 'utenberg" '],
 ['ct, 1914)\n', 't Gutenbeo', ' Gutenbed ', 'Gutenberg,', 'utenberg\n\n']]
tensor([-0.2100, -0.2700, -0.2300, -0.1700, -0.1600], device='cuda:0')
tensor([[-0.2100, -0.2700, -0.2300, -0.1700, -0.1600],
        [-2.1800, -1.8300, -2.0200, -2.9900, -3.7200],
        [-6.0700, -6.5300, -5.9000, -3.7900, -4.5100],
        [-6.4300, -6.6100, -6.7900

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:    9, Loss: 0.8958
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't\nGutenber', ' Gutenberg', 'Gutenberg-', 'uzon Fron\n']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ', 't.\n\n      ', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1914)\n', 't Gutenbed', ' Gutenbed ', 'Gutenberg.', 'utenberg\n\n'],
 ['ct Gutenby', 't, 1914)\n ', ' Gutenbed.', 'Gutenberg,', 'utenberg" ']]
tensor([-0.2300, -0.2400, -0.2200, -0.2500, -0.1900], device='cuda:0')
tensor([[-0.2300, -0.2400, -0.2200, -0.2500, -0.1900],
        [-1.9500, -1.8200, -1.9900, -2.2900, -2.8700],
        [-5.3400, -5.7000, -5.4800, -2.8700, -3.6900],
        [-6.8400, -7.2700, -7

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   10, Loss: 0.8815
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct Gutenba', 't.\n\n      ', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct.\n\n     ', 't, 1914)\n ', ' Gutenbed ', 'Gutenberg"', 'utenberg\n\n'],
 ['ct, 1914)\n', 't Gutenbed', ' Gutenbed.', 'Gutenberg.', 'utenberg" ']]
tensor([-0.1700, -0.2400, -0.1400, -0.1900, -0.2100], device='cuda:0')
tensor([[-0.1700, -0.2400, -0.1400, -0.1900, -0.2100],
        [-2.1600, -1.7400, -2.3900, -2.5200, -2.7700],
        [-6.7700, -6.7600, -6.3100, -3.1300, -3.3600],
        [-6.7800, -7.3900, -7.7

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   11, Loss: 0.8691
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg L']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ', 't.\n\n      ', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1914)\n', 't, 1914)\n ', ' Gunberg-t', 'Gutenberg"', 'utenberg" '],
 ['ct Gutenba', 't Gutenben', ' Gutenbed ', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.1600, -0.1700, -0.1100, -0.1400, -0.1600], device='cuda:0')
tensor([[-0.1600, -0.1700, -0.1100, -0.1400, -0.1600],
        [-2.2100, -2.1900, -2.7700, -2.7300, -2.8900],
        [-6.4400, -6.4100, -6.3200, -3.6200, -3.6700],
        [-7.4700, -7.3700, -7.84

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   12, Loss: 0.8579
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't\nGutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ', 't, 1914)\n ', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1914)\n', 't.\n\n      ', "' Gutenber", 'Gutenberg.', 'utenberg" '],
 ['ct, 1913)\n', 't, 1913)\n ', ', 1914)\n  ', 'Gutenberg,', 'utenberg.o']]
tensor([-0.1800, -0.1900, -0.1400, -0.1000, -0.1300], device='cuda:0')
tensor([[-0.1800, -0.1900, -0.1400, -0.1000, -0.1300],
        [-2.0300, -1.9500, -2.3500, -3.1100, -2.9700],
        [-6.6300, -6.5000, -6.5600, -3.9300, -3.6600],
        [-6.8200, -6.8700, -6

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   13, Loss: 0.8476
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ', 't Gunberg-', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1914)\n', 't, because', "' Gutenber", 'Gutenberg"', 'utenberg" '],
 ['ct Gunstea', 't, 1914)\n ', ' Gutenbed ', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.1100, -0.1100, -0.1000, -0.1400, -0.1700], device='cuda:0')
tensor([[-0.1100, -0.1100, -0.1000, -0.1400, -0.1700],
        [-2.6000, -2.6200, -2.7700, -2.7600, -2.8100],
        [-6.9800, -7.3200, -6.7500, -3.9200, -3.9100],
        [-7.5700, -7.4000, -6.9100

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   14, Loss: 0.8384
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenbetter']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't.\n\n      ', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct Gutenbr', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg.', 'utenberg" '],
 ['ct Gutenba', 't Gutenben', ' Gutenby P', 'Gutenberg"', 'utenberg E']]
tensor([-0.1600, -0.1200, -0.1200, -0.2000, -0.2800], device='cuda:0')
tensor([[-0.1600, -0.1200, -0.1200, -0.2000, -0.2800],
        [-2.1300, -2.3500, -2.4400, -2.2100, -2.2200],
        [-7.6800, -7.4400, -6.8500, -3.5300, -3.4800],
        [-7.8300, -7.6400, -7.8000

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   15, Loss: 0.8299
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg L']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, e.g. 1', 't, Project', ', Project ', 'Gutenberg"', 'utenberg\nL'],
 ['ct Guterat', 't Gutenbed', ', Project\n', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.1800, -0.1300, -0.1100, -0.3500, -0.4100], device='cuda:0')
tensor([[-0.1800, -0.1300, -0.1100, -0.3500, -0.4100],
        [-2.0300, -2.3100, -2.5200, -1.6900, -1.9500],
        [-7.2700, -6.8700, -7.8700, -3.1400, -2.9200],
        [-8.5600, -7.6500, -7.9100, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   16, Loss: 0.8222
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', '\nGutenberg', 'Gutenberg-', 'utenberg L']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ' Gutenbefo', 'Gutenberg\n', 'utenberg\nL'],
 ['ct Guterat', 't Gutenbee', ' Gutenbeer', 'Gutenberg"', 'utenberg" '],
 ['ct Guterba', 't Gutenbed', ' Gutenbed ', 'Gutenberg.', 'utenberg.o']]
tensor([-0.1600, -0.1300, -0.1200, -0.2700, -0.3400], device='cuda:0')
tensor([[-0.1600, -0.1300, -0.1200, -0.2700, -0.3400],
        [-2.1100, -2.2700, -2.3900, -1.8600, -1.8700],
        [-7.6900, -7.3100, -7.7700, -3.2000, -3.2400],
        [-8.0300, -7.6200, -7.8900, -4

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   17, Loss: 0.8145
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ', 't, 1914)\n ', 'G Gutenber', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1914)\n', 't Gutenbed', "' Gutenber", 'Gutenberg"', 'utenberg" '],
 ['ct Gutenbu', 't Gutenbef', ' Gutenbefo', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.2100, -0.2000, -0.1200, -0.1600, -0.1900], device='cuda:0')
tensor([[-0.2100, -0.2000, -0.1200, -0.1600, -0.1900],
        [-1.7900, -1.8300, -2.3900, -2.4800, -2.4000],
        [-7.2800, -7.2700, -6.5300, -3.6200, -3.5700],
        [-7.2800, -8.0800, -7.0200, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   18, Loss: 0.8077
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', '\nGutenberg', 'Gutenberg ', 'utenberg W']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1913)\n', 'h Gutenber', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ct Gutenbu', 't Gutenben', ' Gutenbeng', 'Gutenberg.', 'utenberg E']]
tensor([-0.2200, -0.2100, -0.1300, -0.4100, -0.4100], device='cuda:0')
tensor([[-0.2200, -0.2100, -0.1300, -0.4100, -0.4100],
        [-1.7300, -1.7500, -2.2800, -1.4800, -1.6700],
        [-6.7500, -7.1000, -6.9200, -2.8700, -3.2000],
        [-8.0000, -7.5100, -7.1900, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   19, Loss: 0.8014
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ct Gutent ', 't GUTENBER', ', Project ', 'Gutenberg"', 'utenberg" '],
 ['cting the ', 't Gutenben', ' Gutenbeng', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.1400, -0.1300, -0.1200, -0.1200, -0.2000], device='cuda:0')
tensor([[-0.1400, -0.1300, -0.1200, -0.1200, -0.2000],
        [-2.2100, -2.2300, -2.3600, -2.7400, -2.4300],
        [-8.1000, -7.6900, -7.5300, -3.5900, -3.5900],
        [-8.2400, -8.6300, -8.8400, -4

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   20, Loss: 0.7955
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', 'm Gutenber', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, becaus', 't Gutenben', ' Gutenbeng', 'Gutenberg"', 'utenberg" '],
 ['ct Gutenba', 't, because', ', because ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2400, -0.2500, -0.1200, -0.2500, -0.2000], device='cuda:0')
tensor([[-0.2400, -0.2500, -0.1200, -0.2500, -0.2000],
        [-1.6400, -1.5500, -2.3000, -1.9700, -2.3400],
        [-7.6000, -7.9800, -7.5000, -2.9800, -3.5500],
        [-7.9300, -8.4100, -8.7000, -4

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   21, Loss: 0.7897
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct.\n\n     ', 't, 1914)\n ', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1914)\n', 't Gutenbet', ', Project ', 'Gutenberg"', 'utenberg" '],
 ['ct Gutenba', 't, Project', ' Gutenbeng', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.1700, -0.2400, -0.1500, -0.1400, -0.1900], device='cuda:0')
tensor([[-0.1700, -0.2400, -0.1500, -0.1400, -0.1900],
        [-1.9600, -1.6100, -2.0600, -2.5500, -2.4800],
        [-7.4400, -8.0100, -7.1200, -3.5600, -3.5900],
        [-7.6500, -8.5000, -8.850

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   22, Loss: 0.7844
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 'h Gutenber', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ct, becaus', 't, 1914)\n ', ' Gutenbeer', 'Gutenberg"', 'utenberg" '],
 ['ct Gutenbu', 't Gutenbee', ' Gutenbedr', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.2300, -0.2300, -0.1400, -0.1800, -0.2100], device='cuda:0')
tensor([[-0.2300, -0.2300, -0.1400, -0.1800, -0.2100],
        [-1.6500, -1.6400, -2.1400, -2.2300, -2.2100],
        [-7.6500, -7.7200, -7.9800, -3.5100, -3.5100],
        [-8.4800, -8.2700, -8.0500, -4

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   23, Loss: 0.7793
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg"', 'utenberg" '],
 ['ct, 1913)\n', 't, 1914)\n\n', ', 1914)\n  ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct Gutenbr', 't GUTENBER', "'S Gutenbe", 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2500, -0.2200, -0.1600, -0.1800, -0.2400], device='cuda:0')
tensor([[-0.2500, -0.2200, -0.1600, -0.1800, -0.2400],
        [-1.5600, -1.6600, -2.0100, -2.2700, -2.0900],
        [-6.8100, -7.3000, -7.1700, -3.6900, -3.6000],
        [-7.9500, -8.7100, -7.8600

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   24, Loss: 0.7743
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 'h Gutenber', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, 1913)\n', 't, 1914)\n ', '.\n\n       ', 'Gutenberg"', 'utenberg\nL'],
 ['ct.\n\n     ', 'h\nGutenber', ', Project ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.1600, -0.1200, -0.1500, -0.1700, -0.1600], device='cuda:0')
tensor([[-0.1600, -0.1200, -0.1500, -0.1700, -0.1600],
        [-2.0100, -2.2700, -2.0400, -2.4000, -2.7500],
        [-6.3700, -5.4200, -7.1300, -3.6700, -3.6200],
        [-7.4800, -7.4000, -7.5

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   25, Loss: 0.7697
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct, 1913)\n', 't GUTENBER', ', 1914)\n  ', 'Gutenberg"', 'utenberg\nL'],
 ['ct Gutenbu', 't Gunstenb', ' Gutenbeng', 'Gutenberg:', 'utenberg"\n']]
tensor([-0.2700, -0.2400, -0.1900, -0.1700, -0.2300], device='cuda:0')
tensor([[-0.2700, -0.2400, -0.1900, -0.1700, -0.2300],
        [-1.4900, -1.5800, -1.8300, -2.3200, -2.2900],
        [-7.1700, -8.2700, -7.4000, -3.6000, -3.6300],
        [-8.3200, -8.8800, -8.7400, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   26, Loss: 0.7655
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't\nGutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, 1913)\n', 't, 1913)\n ', '.\n\n       ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1909)\n', 't, 1914)\n\n', ', 1914)\n\n ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2200, -0.1800, -0.1300, -0.2400, -0.2600], device='cuda:0')
tensor([[-0.2200, -0.1800, -0.1300, -0.2400, -0.2600],
        [-1.7200, -1.8500, -2.1800, -2.0000, -2.1100],
        [-5.7400, -6.8000, -7.1200, -3.4800, -3.5100],
        [-7.0100, -8.1000,

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   27, Loss: 0.7610
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ', etc.\n\nMo', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', because ', 'Gutenberg\n', 'utenberg" '],
 ['cted Guten', 'ted Gutenb', ', 1914)\n  ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1913)\n ', ', Project ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2200, -0.2000, -0.1600, -0.2600, -0.3400], device='cuda:0')
tensor([[-0.2200, -0.2000, -0.1600, -0.2600, -0.3400],
        [-1.6900, -1.7500, -1.9900, -1.9000, -1.8800],
        [-7.1600, -8.4400, -8.0200, -3.2800, -2.9200],
        [-7.3500, -8.7600, -8.030

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   28, Loss: 0.7572
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, 1913)\n', 't, 1913)\n ', ', Project ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1912)\n', 't, 1912)\n ', ', Project\n', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.2300, -0.2500, -0.1500, -0.0600, -0.0700], device='cuda:0')
tensor([[-0.2300, -0.2500, -0.1500, -0.0600, -0.0700],
        [-1.6600, -1.5300, -2.0200, -3.4800, -3.4400],
        [-6.7700, -7.8000, -8.0400, -4.5100, -4.7100],
        [-7.6700, -8.7600, -9.29

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   29, Loss: 0.7532
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct.\n\n     ', 't GUTENBER', '.\n\n       ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't\nGUTENBER', ', 1914)\n  ', 'Gutenberg:', 'utenberg"\n']]
tensor([-0.2100, -0.1800, -0.1900, -0.3200, -0.2400], device='cuda:0')
tensor([[-0.2100, -0.1800, -0.1900, -0.3200, -0.2400],
        [-1.7300, -1.8300, -1.8200, -1.5800, -2.1100],
        [-6.3800, -7.4100, -7.0300, -3.2900, -3.6100],
        [-7.1800, -7.8800, -7.4

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   30, Loss: 0.7494
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1913)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ct.\n\n     ', 't Gunsberg', ', 1913)\n  ', 'Gutenberg,', 'utenberg E']]
tensor([-0.3000, -0.2500, -0.2200, -0.1500, -0.2500], device='cuda:0')
tensor([[-0.3000, -0.2500, -0.2200, -0.1500, -0.2500],
        [-1.3900, -1.5300, -1.6400, -2.3100, -1.9800],
        [-7.0000, -7.7600, -7.3200, -4.0300, -3.9000],
        [-7.4500, -8.3200, -7.79

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   31, Loss: 0.7456
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct.\n\n     ', 't.\n\n      ', '.\n\n       ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1913)\n ', ', 1914)\n  ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2400, -0.1700, -0.1800, -0.1300, -0.1900], device='cuda:0')
tensor([[-0.2400, -0.1700, -0.1800, -0.1300, -0.1900],
        [-1.6000, -1.8700, -1.8400, -2.4900, -2.2200],
        [-7.0700, -7.6700, -7.4900, -4.2000, -3.7900],
        [-7.5300, -8.8500, -7

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   32, Loss: 0.7421
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', '\nGutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, 1913)\n', 't) Gutenbe', "' Gutenber", 'Gutenberg"', 'utenberg\nL'],
 ['ct.\n\n     ', 't, 1913)\n ', '.\n\n       ', 'Gutenberg,', 'utenberg E']]
tensor([-0.2700, -0.2000, -0.2000, -0.1000, -0.1200], device='cuda:0')
tensor([[-0.2700, -0.2000, -0.2000, -0.1000, -0.1200],
        [-1.4700, -1.7300, -1.7600, -2.8000, -2.8900],
        [-6.4200, -7.1200, -6.8900, -4.3200, -4.0600],
        [-7.6900, -8.7300, -7.3

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   33, Loss: 0.7391
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ct.\n\n     ', 'ter Gutenb', '.\n\n       ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1913)\n ', ': Gutenber', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.3400, -0.2200, -0.1800, -0.1400, -0.1400], device='cuda:0')
tensor([[-0.3400, -0.2200, -0.1800, -0.1400, -0.1400],
        [-1.2700, -1.6600, -1.8300, -2.6800, -2.7400],
        [-6.8400, -7.2700, -7.9500, -3.5700, -3.7100],
        [-7.6200, -8.4200, -8.

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   34, Loss: 0.7358
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct.\n\n     ', 'ter Gutenb', '.\n\n       ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1913)\n ', ', 1914)\n\n ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2800, -0.1800, -0.1500, -0.2300, -0.1800], device='cuda:0')
tensor([[ -0.2800,  -0.1800,  -0.1500,  -0.2300,  -0.1800],
        [ -1.4500,  -1.8300,  -2.0100,  -2.0100,  -2.4000],
        [ -7.4600,  -7.6400,  -7.8400,  -3.2800,  -3.6200],
        [ -8.

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   35, Loss: 0.7327
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ch Gutenbe', 'ter Gutenb', 'er Gutenbe', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't Gunsberg', ', 1914)\n  ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.1900, -0.1800, -0.1400, -0.1600, -0.1400], device='cuda:0')
tensor([[ -0.1900,  -0.1800,  -0.1400,  -0.1600,  -0.1400],
        [ -1.7900,  -1.8000,  -2.0500,  -2.1800,  -2.4700],
        [ -8.3000,  -8.9900,  -7.5100,  -3.9900,  -4.3200],
        [ -8.5000,  -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   36, Loss: 0.7294
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct.\n\n     ', 't\nGUTENBER', ', Project ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1914)\n\n', ', 1914)\n  ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2100, -0.1700, -0.1400, -0.1200, -0.1000], device='cuda:0')
tensor([[ -0.2100,  -0.1700,  -0.1400,  -0.1200,  -0.1000],
        [ -1.7100,  -1.8700,  -2.0400,  -2.5000,  -2.8900],
        [ -7.6200,  -8.3800,  -7.8800,  -4.2800,  -4.5100],
        [ -8.550

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   37, Loss: 0.7263
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 'h Gutenber', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ch Gutenbe', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ct, 1913)\n', 't\nGUTENBER', ', Project ', 'Gutenberg,', 'utenberg E']]
tensor([-0.2600, -0.2300, -0.2100, -0.1600, -0.1800], device='cuda:0')
tensor([[-0.2600, -0.2300, -0.2100, -0.1600, -0.1800],
        [-1.5000, -1.6100, -1.6700, -2.1600, -2.2100],
        [-8.0200, -8.2700, -8.1600, -3.9000, -4.2400],
        [-8.2500, -8.5100, -8.5800, 

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   38, Loss: 0.7232
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't\nGutenber', ' Gutenberg', 'Gutenberg ', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, 1913)\n', 'ted Gutenb', 'ed Gutenbe', 'Gutenberg"', 'utenberg\nL'],
 ['cting the ', 'ter Gutenb', "' Gutenber", 'Gutenberg:', 'utenberg:\n']]
tensor([-0.1500, -0.1100, -0.1400, -0.1100, -0.0600], device='cuda:0')
tensor([[-0.1500, -0.1100, -0.1400, -0.1100, -0.0600],
        [-2.0000, -2.2500, -2.0600, -2.4900, -3.1700],
        [-8.4400, -8.7600, -7.9000, -4.7100, -5.3200],
        [-9.2000, -9.0500, -8.4400,

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   39, Loss: 0.7205
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't\nGutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct, Projec', 't, 1913)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1914)\n\n', ', Project ', 'Gutenberg:', 'utenberg"\n']]
tensor([-0.2300, -0.1700, -0.1900, -0.2100, -0.1400], device='cuda:0')
tensor([[ -0.2300,  -0.1700,  -0.1900,  -0.2100,  -0.1400],
        [ -1.6000,  -1.8700,  -1.8000,  -2.0900,  -2.5400],
        [ -7.8200,  -7.9800,  -7.4500,  -3.3500,  -3.9000],
        [ -8.550

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   40, Loss: 0.7177
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg\n', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['cts Gutenb', 'ter Gutenb', "' Gutenber", 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 'ts Gutenbe', ', Project ', 'Gutenberg,', 'utenberg"\n']]
tensor([-0.2600, -0.1600, -0.1300, -0.1600, -0.1500], device='cuda:0')
tensor([[-0.2600, -0.1600, -0.1300, -0.1600, -0.1500],
        [-1.4800, -1.9000, -2.1000, -2.2200, -2.3200],
        [-8.2800, -8.4200, -8.3600, -4.2300, -4.1700],
        [-8.9600, -9.1600, -8.7100,

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   41, Loss: 0.7154
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ch Gutenbe', 't\nGUTENBER', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ct Gutenba', 't GUTENBER', ', Project ', 'Gutenberg:', 'utenberg"\n']]
tensor([-0.2000, -0.1700, -0.3000, -0.2100, -0.1600], device='cuda:0')
tensor([[ -0.2000,  -0.1700,  -0.3000,  -0.2100,  -0.1600],
        [ -1.7200,  -1.8600,  -1.3600,  -2.2600,  -2.7800],
        [ -8.5300,  -8.7000,  -8.3900,  -3.0000,  -3.0100],
        [ -8.7800,  -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   42, Loss: 0.7127
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct, becaus', "t' Gutenbe", ', 1914)\n  ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, 1913)\n', 't, 1913)\n ', ', Project ', 'Gutenberg.', 'utenberg"\n']]
tensor([-0.2600, -0.2400, -0.1400, -0.0900, -0.0900], device='cuda:0')
tensor([[ -0.2600,  -0.2400,  -0.1400,  -0.0900,  -0.0900],
        [ -1.4900,  -1.5400,  -2.0900,  -2.7200,  -2.8800],
        [ -8.9700,  -9.0700,  -7.6400,  -4.5600,  -4.7700],
        [ -8.9900,  

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   43, Loss: 0.7103
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', '\nGutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg\nL'],
 ['ct, Projec', 'h Gutenber', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ct, 1913)\n', 't, Project', ', Project ', 'Gutenberg.', 'utenberg E']]
tensor([-0.1900, -0.1900, -0.1200, -0.1400, -0.1100], device='cuda:0')
tensor([[ -0.1900,  -0.1900,  -0.1200,  -0.1400,  -0.1100],
        [ -1.7700,  -1.7800,  -2.2000,  -2.3400,  -2.7500],
        [ -8.1200,  -8.9700,  -8.4000,  -4.0100,  -4.4600],
        [ -8.8900,  -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   44, Loss: 0.7073
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ch Gutenbe', 'h Gutenber', "' Gutenber", 'Gutenberg\n', 'utenberg" '],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg\nL'],
 ['ct, Projec', "t' Gutenbe", 'er Gutenbe', 'Gutenberg:', 'utenberg E']]
tensor([-0.2600, -0.2300, -0.2100, -0.3200, -0.2900], device='cuda:0')
tensor([[-0.2600, -0.2300, -0.2100, -0.3200, -0.2900],
        [-1.4900, -1.6000, -1.6800, -1.6400, -1.9000],
        [-8.2200, -9.2500, -8.5600, -3.1500, -3.5000],
        [-8.5700, -9.3000, -9.5200, -3

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   45, Loss: 0.7053
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, Projec', 't, Project', ', Project ', 'Gutenberg"', 'utenberg\nL'],
 ['cting Gute', 'ted Gutenb', "' Gutenber", 'Gutenberg.', 'utenberg"\n']]
tensor([-0.1900, -0.1400, -0.1200, -0.1700, -0.1000], device='cuda:0')
tensor([[-0.1900, -0.1400, -0.1200, -0.1700, -0.1000],
        [-1.7700, -2.0700, -2.2100, -2.1600, -2.8000],
        [-8.5100, -8.4200, -7.0200, -3.9200, -4.6700],
        [-8.7700, -9.3900, -8.0200, -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   46, Loss: 0.7030
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg\nL'],
 ['ch Gutenbe', 't, Project', ', Project ', 'Gutenberg"', 'utenberg" '],
 ['ct, 1914. ', 'ted Gutenb', 'ed Gutenbe', 'Gutenberg:', 'utenberg:\n']]
tensor([-0.1600, -0.1200, -0.0900, -0.1000, -0.1200], device='cuda:0')
tensor([[ -0.1600,  -0.1200,  -0.0900,  -0.1000,  -0.1200],
        [ -1.9300,  -2.1700,  -2.4700,  -2.5600,  -2.4700],
        [ -8.8100,  -8.7300,  -7.8800,  -4.6200,  -4.8400],
        [ -8.9000,  -9

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   47, Loss: 0.7004
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ch Gutenbe', 't, 1914)\n ', "' Gutenber", 'Gutenberg\n', 'utenberg E'],
 ['ct, 1914)\n', 't, Project', ', 1914)\n  ', 'Gutenberg,', 'utenberg\nL'],
 ['ct, 1913)\n', 't Gunsberg', ', Project ', 'Gutenberg.', 'utenberg" ']]
tensor([-0.1600, -0.1500, -0.1400, -0.3700, -0.2300], device='cuda:0')
tensor([[ -0.1600,  -0.1500,  -0.1400,  -0.3700,  -0.2300],
        [ -1.9300,  -1.9800,  -2.0400,  -1.3300,  -1.9900],
        [ -8.9300,  -8.8900,  -8.4800,  -3.6000,  -4.1600],
        [ -8.9300,  -9

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   48, Loss: 0.6984
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg\n', 'utenberg" '],
 ['ct, 1909)\n', 't, Project', "' Gutenber", 'Gutenberg"', 'utenberg\nL'],
 ['ct Guterba', 't, 1913)\n ', ', Project ', 'Gutenberg,', 'utenberg W']]
tensor([-0.2300, -0.2000, -0.1300, -0.2600, -0.1700], device='cuda:0')
tensor([[ -0.2300,  -0.2000,  -0.1300,  -0.2600,  -0.1700],
        [ -1.6000,  -1.7300,  -2.1400,  -1.6700,  -2.2800],
        [ -8.6500,  -8.6100,  -8.2900,  -4.0400,  -4.3100],
        [-10.1300, -1

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   49, Loss: 0.6962
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct\nGutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, 1914)\n', 't, 1914)\n ', ', Gutenber', 'Gutenberg\n', 'utenberg" '],
 ['cting Gute', 't, Project', ', Project ', 'Gutenberg"', 'utenberg\nL'],
 ['cting the ', 'ted Gutenb', ', 1914)\n  ', 'Gutenberg,', 'utenberg E']]
tensor([-0.2400, -0.2300, -0.2500, -0.1100, -0.0800], device='cuda:0')
tensor([[-0.2400, -0.2300, -0.2500, -0.1100, -0.0800],
        [-1.5500, -1.5800, -1.5400, -2.5000, -2.9900],
        [-8.8300, -9.4400, -8.1100, -4.3400, -4.9500],
        [-9.4700, -9.6800, -8.7000, -

  0%|          | 0/3713 [00:00<?, ?it/s]

Epoch:   50, Loss: 0.6944
Y
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg E']
forward
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-L']
greedy_search
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t']
sample
['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg ', 'utenberg-t']
beam_search
[['ct Gutenbe', 't Gutenber', ' Gutenberg', 'Gutenberg-', 'utenberg-t'],
 ['ct\nGutenbe', 't\nGutenber', '\nGutenberg', 'Gutenberg ', 'utenberg L'],
 ['ct, Projec', 't, 1914)\n ', ', 1914)\n  ', 'Gutenberg"', 'utenberg" '],
 ['ct, 1914)\n', 't, Project', ', Project ', 'Gutenberg\n', 'utenberg\nL'],
 ['ct, Gutenb', 't\nGUTENBER', "' Gutenber", 'Gutenberg,', 'utenberg\na']]
tensor([-0.1700, -0.1200, -0.1200, -0.1300, -0.1200], device='cuda:0')
tensor([[-0.1700, -0.1200, -0.1200, -0.1300, -0.1200],
        [-1.8700, -2.1600, -2.1700, -2.5500, -2.7700],
        [-8.3700, -8.5800, -8.2000, -4.1000, -4.1300],
        [-8.6400, -9.7600, -8.3200, 

In [12]:
pprint([net.tensor2text(t) for t in net.beam_search(source_1[:10], 
                                                    max_predictions = 50, 
                                                    candidates = 10,
                                                    beam_width = 10)[0][:, :, 1:]], compact = True)

RuntimeError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 15.78 GiB total capacity; 5.48 GiB already allocated; 9.00 MiB free; 5.50 GiB reserved in total by PyTorch)